apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-johnpofo-monapp3-frontend-cert
  namespace: dev-johnpofo-monapp3-frontend
spec:
  secretName: dev-johnpofo-monapp3-frontend-tls
  dnsNames:
    - dev.mydomain.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
