apiVersion: v1
kind: Service
metadata:
  name: dev-johnpofo-monapp3-frontend-service
  namespace: dev-johnpofo-monapp3-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: dev-johnpofo-monapp3-frontend
