apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-johnpofo-monapp3-frontend-cert
  namespace: staging-johnpofo-monapp3-frontend
spec:
  secretName: staging-johnpofo-monapp3-frontend-tls
  dnsNames:
    - staging.mydomain.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
