apiVersion: v1
kind: Service
metadata:
  name: staging-johnpofo-monapp3-frontend-service
  namespace: staging-johnpofo-monapp3-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: staging-johnpofo-monapp3-frontend
