apiVersion: v1
kind: Service
metadata:
  name: prod-johnpofo-monapp3-frontend-service
  namespace: prod-johnpofo-monapp3-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: prod-johnpofo-monapp3-frontend
